import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://www.leobrain.com/');
  await page.getByRole('button', { name: 'Start Free Today Start Free' }).click();
  await page.getByRole('button', { name: 'Sign In' }).click();
  await page.getByRole('textbox', { name: 'Email ID' }).click();
  await page.getByRole('textbox', { name: 'Email ID' }).fill('dharmi.ajagiya@coretus.com');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('Dharmi@123');
  
  await page.getByRole('button', { name: 'Sign In' }).click();
  await page.waitForLoadState('networkidle');
  await page.getByRole('button', { name: 'Jobs' }).click();
  await page.getByRole('button', { name: 'Create Job' }).click();
  await page.getByRole('textbox', { name: 'Job Title' }).click();
  await page.getByRole('textbox', { name: 'Job Title' }).fill('Business analyst');
  await page.getByRole('combobox', { name: 'Department' }).click();
  await page.getByRole('option', { name: 'Finance' }).click();
  await page.getByRole('combobox', { name: 'Work shift' }).click();
  await page.getByLabel('Weekend Shift').getByText('Weekend Shift').click();
  await page.getByRole('button').filter({ hasText: /^$/ }).nth(1).click();
  await page.getByRole('button').filter({ hasText: /^$/ }).nth(1).click();
  await page.getByRole('radio', { name: 'Remote' }).click();
  await page.locator('#date').click();
  await page.getByRole('button', { name: 'Wednesday, December 31st,' }).click();
  await page.getByRole('combobox', { name: 'Company Name' }).click();
  await page.getByRole('option', { name: 'Coretus' }).click();
  await page.getByRole('combobox', { name: 'Location' }).click();
  await page.getByLabel('ahmdabad , gujrat, sasd, Gədə').getByText('ahmdabad , gujrat, sasd, Gədə').click();
  await page.getByRole('combobox', { name: 'Experience' }).click();
  await page.getByRole('option', { name: '-10 Years' }).click();
  await page.getByRole('combobox', { name: 'Employment Type' }).click();
  await page.getByRole('option', { name: 'Temporary' }).click();
  await page.getByRole('combobox', { name: 'Education (Optional)' }).click();
  await page.getByRole('option', { name: 'Diploma / Certificate' }).click();
  await page.getByRole('combobox', { name: 'Additional Perks (Optional)' }).click();
  await page.locator('div').filter({ hasText: /^Transport$/ }).click();
  await page.getByText('Performance Bonuses').click();
  await page.getByText('Overtime Pay').click();
  await page.locator('html').click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.getByRole('button', { name: 'Generate' }).click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.getByRole('combobox', { name: 'Pay Structure' }).click();
  await page.getByRole('option', { name: 'Hourly Wage' }).click();
  await page.getByRole('combobox', { name: 'Pay Terms' }).click();
  await page.getByRole('option', { name: 'Annually' }).click();
  await page.getByRole('combobox', { name: 'Currency' }).click();
  await page.getByRole('option', { name: 'CHF' }).click();
  await page.getByRole('radio', { name: 'Upto' }).click();
  await page.getByRole('spinbutton', { name: 'Amount' }).click();
  await page.getByRole('spinbutton', { name: 'Amount' }).fill('19999');
  await page.getByRole('combobox', { name: 'Recruiter Name' }).click();
  await page.getByRole('option', { name: 'Dharmi Ajagiya' }).click();
  await page.getByRole('combobox', { name: 'Country selector' }).click();
  await page.getByRole('option', { name: 'Hong Kong +' }).click();
  await page.locator('input[name="phone"]').click();
  await page.locator('input[name="phone"]').fill('+852 3453 45345');
  await page.getByRole('button', { name: 'Next' }).click();
  await page.getByRole('textbox', { name: 'Question' }).click();
  await page.getByRole('textbox', { name: 'Question' }).fill('dgfgdfgdfg');
  await page.getByRole('combobox', { name: 'Type' }).click();
  await page.getByLabel('Single Select').getByText('Single Select').click();
  await page.locator('input[type="text"]').click();
  await page.locator('input[type="text"]').fill('dfgdfgdfg');
  await page.getByRole('button', { name: 'Option' }).click();
  await page.getByRole('textbox').nth(2).click();
  await page.getByRole('textbox').nth(2).fill('gdfgdfgd');
  await page.getByRole('button', { name: 'Option' }).click();
  await page.getByRole('textbox').nth(3).click();
  await page.getByRole('textbox').nth(3).fill('gdfgdfgd');
  await page.locator('#is_mandatory').click();
  await page.getByRole('button', { name: 'Add Question' }).click();
  await page.getByRole('textbox', { name: 'Question' }).click();
  await page.getByRole('textbox', { name: 'Question' }).fill('gdfgdfgdfgdf');
  await page.getByRole('combobox', { name: 'Type' }).click();
  await page.getByLabel('Long Answer').getByText('Long Answer').click();
  await page.getByRole('button', { name: 'Add Question' }).click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.getByRole('button', { name: 'Stage' }).click();
  await page.getByRole('textbox', { name: 'Name' }).click();
  await page.getByRole('textbox', { name: 'Name' }).fill('gdfgdfgdfgd');
  await page.getByRole('textbox', { name: 'Short Description' }).click();
  await page.getByRole('textbox', { name: 'Short Description' }).fill('fgdgdfgd');
  await page.getByRole('button', { name: 'Add' }).click();
  await page.getByRole('button', { name: 'Stage' }).click();
  await page.getByRole('textbox', { name: 'Name' }).click();
  await page.getByRole('textbox', { name: 'Name' }).fill('gdfgdfgdfg');
  await page.getByRole('textbox', { name: 'Short Description' }).click();
  await page.getByRole('textbox', { name: 'Short Description' }).fill('rtertet');
  await page.getByRole('radio', { name: 'Assessment' }).click();
  await page.getByRole('combobox', { name: 'Moderator' }).click();
  await page.getByLabel('Dharmi Ajagiya').getByText('Dharmi Ajagiya').click();
  await page.getByRole('combobox', { name: 'Assessment' }).click();
  await page.getByRole('option', { name: 'Testing' }).click();
  await page.getByRole('button', { name: 'Add' }).click();
  await page.getByRole('button', { name: 'Publish' }).click();
  await page.getByRole('button', { name: 'Yes' }).click();
  await page.getByRole('button', { name: 'Okay' }).click();
});

